line-length = 150
# Read more here https://beta.ruff.rs/docs/rules/
# By default, Ruff enables Flake8's E and F rules
# Pyflakes - F, pycodestyle - E, W
# flake8-builtins - A
# Pylint - PLC, PLE, PLW
# isort - I
# Docstrings - D
select = [
    'E',    # Syntax errors
    'F',    # Pyflakes
    'W',    # pycodestyle
    'A',    # flake8-builtins
    'PLC',  # Pylint
    'PLE',  # Pylint
    'PLW',  # Pylint
    'I',    # isort
    'D',    # Docstrings
]