name: development

on:
  push:
    branches:
      - 'development'
      - 'feature/*'
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - 'development'
      - 'feature/*'
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/**'

jobs:
  ruff-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install --with dev

      - name: Run Mypy (Static Type Checking)
        run: poetry run mypy src

  ruff-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install --with dev

      - name: Run Ruff (Linting)
        run: poetry run ruff check

  bandit-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install --with dev

      - name: Run Bandit (Security Analysis)
        run: poetry run bandit -c pyproject.toml -r src

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install --with dev

      - name: Run Pytest (Tests and Coverage)
        run: poetry run pytest


  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install --with dev

      - name: Run Pytest (Tests)
        run: poetry run coverage run --source=src -m pytest

      - name: Run Coverage (Report)
        run: poetry run coverage report -m --fail-under=50

      - name: Run Coverage (HTML Report)
        run: poetry run coverage html

      - name: Run Coverage (Codecov Report)
        run: poetry run coverage xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
